services:
    omnifarming-rofl:
        image: "docker.io/ghoulouis/omnifarming-rofl:latest"
        platform: linux/amd64
        environment:
            - IS_PRODUCT=true
            - AGENT_EVM_PRIVATE_KEY=${AGENT_EVM_PRIVATE_KEY}
            - CENTIC_API_KEYS=${CENTIC_API_KEYS}
