name: omnifarming-rofl
services:
    omnifarming-rofl:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: omnifarming-rofl
        platform: linux/amd64
        environment:
            - IN_ROFL=TRUE
            - AGENT_EVM_PRIVATE_KEY=${AGENT_EVM_PRIVATE_KEY}
            - CENTIC_API_KEYS=${CENTIC_API_KEYS}
            - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
            - TELEGRAM_GROUP_ID=${TELEGRAM_GROUP_ID}
        image: ghoulouis/thorn-omnifarming-rofl
