version: "3.8"
name: omnifarming-rofl
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        image: ghoulouis/thorn-omnifarming-rofl
        container_name: v2-server
        environment:
            - IN_ROFL=TRUE
            - AGENT_EVM_PRIVATE_KEY=${AGENT_EVM_PRIVATE_KEY}
            - CENTIC_API_KEYS=${CENTIC_API_KEYS}
            - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
            - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
            - TELEGRAM_GROUP_ID=${TELEGRAM_GROUP_ID}
        restart: on-failure
